#theme: jekyll-theme-cayman
title: SC Student Cluster Competition History
description: The history of the annual SC Student Cluster Competition.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
